### ISSUE TITLE
Request GetHumanStatus{model: ArrayObject} is not supported on payment done controller

### ISSUE THREAD

**Issue by ateixeira** [Payum/PayumLaravelPackage#12]
Hello,

I'm working with the new 0.11.1 package (thanks for the corrections), and facing the above error on:

```
$status = new GetHumanStatus($token);
$payment->execute($status);
```

i.e.:
I'm redirected from PaypalController on 

```
return $captureToken->getTargetUrl(); 
```

to **http://localhost:8000/csi/payment_done?payum_token=_lLGI4Mxk-UKX4FNUiyq0j94IrY_iLjRoMZfWc8Bdg0**

I can see on my storage the files **payum-model-_lLGI4Mxk-UKX4FNUiyq0j94IrY_iLjRoMZfWc8Bdg0** and **payum-model-5417d0934a306**

The $token resultant from

```
$request = \App::make('request');
$request->attributes->set('payum_token', $payum_token);
$token = $this->getHttpRequestVerifier()->verify($request);
```

Gives me the result:

```
$token->getDetails() = Payum\Core\Model\ArrayObject#5417d0934a306
$token->getHash() = _lLGI4Mxk-UKX4FNUiyq0j94IrY_iLjRoMZfWc8Bdg0
$token->getPaymentName() = paypal-pro
```

If I try to reach payment_done controller with an invalid payum_token, it gives the  error: **A token with hash `_lLGI4Mxk-UKX4FNUiyq0j94IrY_iLjRoMZfWc8Bdg1` could not be found.** and if I try it with a valid token the **Request GetHumanStatus{model: ArrayObject} is not supported**. As I can see on storage a token with equivalent $token details arrayobject ID, I guess my $payments is not properly constructed on config.php.

Can you guys give me a hint on how to validate it?

Regards

**Comment by shoaibgits** [comment]
I got the error:
Request GetHumanStatus{model: ArrayObject} is not supported. while using the Sofort payment method
