### ISSUE TITLE
Create payment refund on Laravel Package

### ISSUE THREAD

**Issue by ateixeira** [Payum/PayumLaravelPackage#17]
Hello Maksim,

I'm having great experience with Payum library. Now I face the need to make Refund operations and want to contribute with the resultant code. 

I've found the question http://stackoverflow.com/q/22965278/955183, talking about how to make it on Payum Bundle.. It's an excellent guideline, now I want just to ask if there are any Laravel Package specific tips so I can make it the best way.

Thanks in advance,
Teixeira

**Comment by jasonherndon** [comment]
Hey - I'm building a Laravel site with Authorize.net integration and refunds are very important to us. Is this already supported with Payum or is the work still ongoing? If it's still ongoing, I'd love to contribute.

**Comment by makasim** [comment]
@jasonherndon core and package itself supports refund requests but unfortunately authorize net extensiion does not yet. paypal pro checkout is the only one payment that supports refund atm. You can use it as an example.

**Comment by jasonherndon** [comment]
@makasim Gotcha. I guess for the time being, if we needed to before we finished a package we could just refund it manually through Auth.net's portal. Thanks - I'll take a look at the paypal pro checkout package.
