### ISSUE TITLE
does this package support laravel 5

### ISSUE THREAD

**Issue by Amin-z** [Payum/PayumLaravelPackage#20]
hello, I am trying to install it on Laravel 5, but unable to, keep getting this error:
```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for payum/payum-laravel-package 0.13.* -> satisfiable
 by payum/payum-laravel-package[0.13.0].
    - Can only install one of: payum/core[0.14.0, 0.13.0].
    - payum/stripe 0.14.0 requires payum/core 0.14.* -> satisfiable by payum/cor
e[0.14.0].
    - payum/payum-laravel-package 0.13.0 requires payum/core 0.13.* -> satisfiab
le by payum/core[0.13.0].
    - Installation request for payum/stripe 0.14.* -> satisfiable by payum/strip
e[0.14.0].
Installation failed, reverting ./composer.json to its original content.
```
also asked this question on StackOverFlow:
http://stackoverflow.com/questions/28977789/laravel-5-unable-to-install-payum-package

**Comment by makasim** [comment]
The version (0.13.0) you are trying to install does not, but there is a newer version of Payum 0.14.0 which supports Laravel5. Try to update deps on Payum. Pay attention that there are some BC breaks so it is not safe to just update deps, you have to tests your code and fix broken things.

**Comment by SharkIng** [comment]
The Document that on your website is not up-to-dated for Laravel 5, when i follow this to install the Payum, it wont successfully installed

**Comment by makasim** [comment]
What problem did you faced?

**Comment by ribagek** [comment]
Get it started docs describe how to configure the package for L4 (bootstrap/start.php). Where to put that config block in L5?

**Comment by makasim** [comment]
The latest version 1.0 does not require any configs at all.
