### ISSUE TITLE
Call to undefined method [package] on Laravel 5

### ISSUE THREAD

**Issue by SharkIng** [Payum/PayumLaravelPackage#21]
its seem newest Laravel 5 delete the method Package?

or its juts i am doing some thing wrong?

I am getting this udefined method error when i try to use Payum as payment system on Laravel 5

**Comment by makasim** [comment]
Are you using stable Payum extension (0.14) or master. Master is not working right now because of the changes in the Payum's Core. They are not synced yet

**Comment by SharkIng** [comment]
I've tried 0.14 and 0.15-dev, neither one works. Because I am using the Newest Laravel 5 version and it's not compatible with your system. 

On ![Dec 4 Commit](https://github.com/laravel/framework/commit/64c15a35d9578748671639748b83b21d16dbd6c2#diff-e4e6c1b4ddc0ce8f5aa571f6c5c2a72dL233)

Leravel team recreate a new package handle system where delete the package() method. and in your package, its seem still using the package() method which cause the problem. 

Hope the comping update will solve it.

Thanks

**Comment by makasim** [comment]
I looked at the commit and I see that the method was removed but  I cannot find any hints on how to "migrate" package from laravel4 to laravel5 or make both version works. 

Could you point me out on some docs about it?

**Comment by SharkIng** [comment]
Hey, Thanks you for considering my issue. I don't really have any example but just simply take look at Laravel 5's document you may get answers http://laravel.com/docs/master/packages

Thanks again

**Comment by SharkIng** [comment]
and this post give some detail https://laracasts.com/discuss/channels/general-discussion/l5-latest-commit-breaks-if-using-waygenerators-or-image-internvention/?page=2

**Comment by makasim** [comment]
reverted support of laravel5 from composer for now https://github.com/Payum/PayumLaravelPackage/commit/2fce92d6cdf9dea7e8476ec85c69eccf96ffd636

**Comment by sdeering** [comment]
So to confirm this package currently doesn't support L5?

**Comment by makasim** [comment]
yes it is.

**Comment by makasim** [comment]
I was not able to find a good tutorial or upgrade manual so I skip it for now

**Comment by sdeering** [comment]
I am unable to install the package using composer. Which version do I use for L5?

I've tried "0.15" and "1.0-dev". Both give me errors on a clean L5 install.

**Comment by makasim** [comment]
IT DOES NOT WORK WITH L5

**Comment by sdeering** [comment]
Ok that is now clear lol ^_^

**Comment by makasim** [comment]
The fix https://github.com/Payum/PayumLaravelPackage/pull/22
