### ISSUE TITLE
Payum\Paypal\ExpressCheckout\Nvp\PaymentFactory::create() should not be called statically, 

### ISSUE THREAD

**Issue by carlosrochap** [Payum/PayumLaravelPackage#25]
So all of a sudden my payments stopped working, I'm guessing this have something to do with an update?, so no backward support ?

**Comment by makasim** [comment]
Yes, there may be some BC breaks between releases like 0.14.x to 0.15.x but there should not be any between 0.14.1 to 0.14.2 for example 

I am trying to document all BC breaks here https://github.com/Payum/Payum/blob/master/UPGRADE.md


Also when 1.0 is released it means no more BC breaks
