### ISSUE TITLE
Composer install fails laravel 5.1

### ISSUE THREAD

**Issue by HarryBosh** [Payum/PayumLaravelPackage#28]
Your requirements could not be resolved to an installable set o                            f packages.

  Problem 1
    - Installation request for payum/payum-laravel-package ^0.1                            5.0 -> satisfiable by payum/payum-laravel-package[0.15.0].
    - Conclusion: remove laravel/framework v5.1.18
    - Conclusion: don't install laravel/framework v5.1.18

also note:
there is no bootstrap/start.php file to put:
App::resolving('payum.builder', function(\Payum\Core\PayumBuilder $payumBuilder) {
    $payumBuilder
        ->addGateway('offline', ['factory' => 'offline'])
    ;
});

into, should this be created? or are the docs wrong, or does this not support laravel 5.+?

either way i will look for another solution in the mean time.

**Comment by juliankoehn** [comment]
This Package is not updated for L5.*

**Comment by makasim** [comment]
In fact the package support laravel 5.1. 

The support was added https://github.com/Payum/PayumLaravelPackage/pull/24/files

**Comment by makasim** [comment]
composer: https://github.com/Payum/PayumLaravelPackage/blob/master/composer.json#L38

**Comment by makasim** [comment]
0.15.0 does not support laravel 5
