### ISSUE TITLE
Does this package support laravel 5.2?

### ISSUE THREAD

**Issue by GopaThemes** [Payum/PayumLaravelPackage#30]
Hello, I want to use this package with Laravel 5.2.*. Does this support the 5.2.*? If yes, where I can get updated documentation? Because on this [thread](https://github.com/Payum/PayumLaravelPackage/issues/20) @makasim said: "The latest version 1.0 does not require any configs at all.". But on the [offical website docs](http://payum.org/doc/1.0/PayumLaravelPackage/get-it-started) and on [github docs](https://github.com/Payum/PayumLaravelPackage/blob/master/docs/get-it-started.md) I can see the author is talking about to place the configuration code. Also the file bootstrap/start.php is not exist.

Where should I place the configuration code?

thank you

**Comment by makasim** [comment]
Most probably [yes it is](https://github.com/Payum/PayumLaravelPackage/pull/31)

**Comment by serpentblade** [comment]
bootstrap/start.php doesn't exist in Laravel 5.2, which isn't a problem since that file was always a bit of a hack.  Put that configuration code into the app/Providers/AppServiceProvider.php:

    ...
    public function register()
    {
        $this->app->resolving('payum.builder', function(\Payum\Core\PayumBuilder $payumBuilder) {
                $payumBuilder
                // this method registers filesystem storages, consider to change them to something more
                // sophisticated, like eloquent storage
                ->addDefaultStorages()

                ->addGateway('paypal_ec', [
                    'factory' => 'paypal_express_checkout',
                    'username' => 'EDIT ME',
                    'password' => 'EDIT ME',
                    'signature' => 'EDIT ME',
                    'sandbox' => true
                ]);
            });
    }
    ...

**Comment by makasim** [comment]
@serpentblade Could you please send the PR with fix for the doc?
