### ISSUE TITLE
Getting 0 as hash for the targetUrl

### ISSUE THREAD

**Issue by perryborst** [Payum/PayumLaravelPackage#33]
Trying to get the eloquent storage to work for payum in laravel 5.2.

I get the error:

`Argument 1 passed to iterator_to_array() must implement interface Traversable, instance of Payum\LaravelPackage\Model\Payment given`

Thrown by   `'details' => iterator_to_array($status->getFirstModel())` in the method that handles the callback of payment_done

In my AppServiceProvider.php i have

```php
<?php
$this->app->resolving('payum.builder', function(\Payum\Core\PayumBuilder $payumBuilder) {
			$payumBuilder
			// this method registers filesystem storages, consider to change them to something more
			// sophisticated, like eloquent storage
			//->addDefaultStorages()
			
			->addStorage(Payment::class, new EloquentStorage(Payment::class))
			->setTokenStorage(new EloquentStorage(Token::class))
	
			->addGateway('paypal_ec', [
				'factory' => 'paypal_express_checkout',
				'username' => 'EDIT ME',
				'password' => 'EDIT ME',
				'signature' => 'EDIT ME',
				'sandbox' => true
			]);
		});
```
My routes:
`
	Route::get('/payment', 'PaypalController@prepareExpressCheckout');
	Route::get('/payment/done/{payum_token}', ['as' => 'payment_done', 'uses' => 'PaypalController@done']);`

Controller:
```php
<?php

namespace App\Http\Controllers;
// app/controllers/PaypalController.php

use Payum\Core\Request\GetHumanStatus;
use Payum\LaravelPackage\Controller\PayumController;
use Symfony\Component\HttpFoundation\Request;


class PaypalController extends PayumController
{
    public function prepareExpressCheckout()
    {
        //$storage = $this->getPayum()->getStorage('Payum\Core\Model\ArrayObject');
		$storage = $this->getPayum()->getStorage('Payum\LaravelPackage\Model\Payment');
		
		/*
        $details = $storage->create();
        $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'EUR';
        $details['PAYMENTREQUEST_0_AMT'] = 1.23;
        $storage->update($details);
		*/
		
		$payment = $storage->create();
         $payment->setNumber(uniqid());
         $payment->setCurrencyCode('EUR');
         $payment->setTotalAmount(1.23); // 1.23 EUR
         $payment->setDescription('A description');
         $payment->setClientId('anId');
         $payment->setClientEmail('foo@example.com');
         $payment->setDetails(array(
           // put here any fields in a gateway format.
           // for example if you use Paypal ExpressCheckout you can define a description of the first item:
           'L_PAYMENTREQUEST_0_DESC' => 'A desc',
		   'L_PAYMENTREQUEST_0_AMT' => 1.23
         ));
         $storage->update($payment);

		
		print_r($this->getPayum()->getTokenFactory());

        $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken('paypal_ec', $payment, 'payment_done');
		
		echo $captureToken->getTargetUrl();

        return \Redirect::to($captureToken->getTargetUrl());
    }
	
	public function done($payum_token)
    {
        
		/** @var Request $request */
        $request = \App::make('request');
        $request->attributes->set('payum_token', $payum_token);

        $token = $this->getPayum()->getHttpRequestVerifier()->verify($request);
        $gateway = $this->getPayum()->getGateway($token->getGatewayName());

        $gateway->execute($status = new GetHumanStatus($token));

        return \Response::json(array(
            'status' => $status->getValue(),
            'details' => iterator_to_array($status->getFirstModel())
        ));
    }
}
```

I've been at it for two evenings and getting nowhere. The package looks promising, so i hope somebody can help me. If i get it working i promise i will write detailed documentation for laravel 5.2 users!

**Comment by makasim** [comment]
> Thrown by 'details' => iterator_to_array($status->getFirstModel()) in the method that handles the callback of payment_done

The done is just an example of what you can do there, you are expected to put your own logic there. The payment is done, get it status and act accordingly.

**Comment by makasim** [comment]
The fix to make it work:

```php
<?php
return \Response::json(array(
            'status' => $status->getValue(),
            'details' => iterator_to_array($status->getFirstModel()->getDetails())
        ));
```

But I advice you to completely rewrite the done action.

**Comment by makasim** [comment]
> Getting 0 as hash for the targetUrl

The issue title is a bit confusing and does not correlate with the issue body. Do you still have a problem with hash or the iterator issue is the only you face for now.

**Comment by perryborst** [comment]
He Maksim,

Thanx for your reply! The 0 hash problem is fixed, i was behind a little bit and i didn't have the latest update in the Token Class. The other issue is not really an issue as i was able to get the details in a different way. (it was too late last night i'm afraid and my brains allready had shut down i believe)

Thnx a lot for your quick reply and a very nice framework! Shall i write some spoecific laravel 5.2 documentation? I can imagine users that just started with laravel will need some time to get it all together.

**Comment by makasim** [comment]
>Thnx a lot for your quick reply and a very nice framework! Shall i write some spoecific laravel 5.2 documentation?

That would be great. I am not laravel dev so it was always hard to show the laravel way

**Comment by perryborst** [comment]
Will do, give me a couple of days to make it a bit more complete and i'll put thorough walk-through in the wiki of the PayumLaravelPackage.

**Comment by 2mellow** [comment]
I am trying to get this working for laravel 5.2. Some documentation or help would be greatly appreciated!
