### ISSUE TITLE
Class payum does not exist

### ISSUE THREAD

**Issue by alukra** [Payum/PayumLaravelPackage#34]
Hi I'm using PayumLaravelPackage in L5.1, this issue I think that is similar to #6 I used the get it started of the docs but the service provider in the doc is 

`return array(
    'providers' => array(
        'Payum\LaravelPackage\PayumServiceProvider',
    ),
);`

In L5 I think tha it used something different like this
`Payum\LaravelPackage\PayumServiceProvider::class,`
I put in this way in my serviceprovicers

L5 dont get me any troubles so I tried to test using my controller like the example of the docs
`
use Illuminate\Http\Request;
use Payum\LaravelPackage\Controller\PayumController;

use App\Http\Requests;
use App\Http\Controllers\Controller;

class AuthorizeController extends PayumController{
    
    public function prepareExpressCheckout(){
      $storage = $this->getPayum()->getStorage('Payum\Core\Model\ArrayObject');

      $details = $storage->create();
      $details['PAYMENTREQUEST_0_CURRENCYCODE'] = 'EUR'; 
      $details['PAYMENTREQUEST_0_AMT'] = 1.23; 
      $storage->update($details);

      $captureToken = $this->getPayum()->getTokenFactory()->createCaptureToken('authorize_net', $details, 'payment_done');

      return \Redirect::to($captureToken->getTargetUrl());
    }

}`

but it always send me ReflectionException in Container.php line 741: Class payum does not exist 
I use the last version of this Package but I don't understand how to get correctly the class.

Thanks

**Comment by makasim** [comment]
Last time I tried it (6 months ago) it worked fine. I pretty sure payum itself works fine so the problem comes from misuse\misconfiguration\bug in larvel+payum integration. 

If you happen to find a solution post it here or better send a PR.
