### ISSUE TITLE
Request Cancel{model: ArrayObject} is not supported

### ISSUE THREAD

**Issue by drtzack** [Payum/PayumLaravelPackage#36]
These are works good for offline
        $gateway->execute($status = new Capture($token));
        $gateway->execute($status = new Authorize($token));
        $gateway->execute($status = new GetHumanStatus($token));
But Cancel doesn't work.
        $gateway->execute($status = new Cancel($token));

Request Cancel{model: ArrayObject} is not supported. Make sure the gateway supports the requests and there is an action which supports this request (The method returns true). There may be a bug, so look for a related issue on the issue tracker.

Is it a bug? Or Isn't there any Cancel Request for Offline?

Can you tell me the list of requests that I can use for offline?

like 
        $gateway->execute($currency = new GetCurrency('TRY'));
        $gateway->execute($status = new Capture($token));
        $gateway->execute($status = new Authorize($token));
        $gateway->execute($status = new GetHumanStatus($token));
etc etc

**Comment by makasim** [comment]
The offline gateways does not support it (could be added though).

**Comment by makasim** [comment]
> Can you tell me the list of requests that I can use for offline?

No I cannot tell you, look at the code.
