### ISSUE TITLE
Is this Compatible with latest laravel? 5.2 or 5.3?

### ISSUE THREAD

**Issue by g0ld3lux** [Payum/PayumLaravelPackage#42]
Hi im Just wondering if this is compatible with latest laravel 
thanks

**Comment by makasim** [comment]
I dont know cuz I do not use Laravel at all and nobody gives me such feedback.

**Comment by makasim** [comment]
It worked with 5.x though not sure about 5.2, 5.3

**Comment by g0ld3lux** [comment]
I see there are some deprecated laravel functionalities like // bootstrap/start.php
It should be added now in App\Providers\AppServiceProvider.php

I tried using this package.. its compatible to 5.2 not 5.3 ( since the it needs some tweaking for the routes , since 5.3 changes the directory of the routes.php)

i also tried this package same , only up to 5.2...

https://github.com/recca0120/laravel-payum

but i have some problem involving it...

And i cant find an example even in this repo or the main repo of payum

about using database (eloquent) for  gatewayconfig

Since i Wanna Store me and my users gateway config in the database

i tried to translate the original plain php docs to adopt in that package...

from config , to controller but im not going near the result i want coz im facing error...

hope you can look at this and see if what might you sugguest....

https://github.com/recca0120/laravel-payum/issues/7

**Comment by makasim** [comment]
It [works](https://github.com/Payum/PayumLaravelPackage/pull/43#issuecomment-280275681) on 5.4  so my guess it works for 5.2, 5.3 too.
