### ISSUE TITLE
Request GetHumanStatus{model: ArrayObject} is not supported.

### ISSUE THREAD

**Issue by shoaibgits** [Payum/PayumLaravelPackage#44]
Using the Sofort Method on my project all the configuration is done now at the capture step it gives error as 
     `Request GetHumanStatus{model: ArrayObject} is not supported.`

My config file is as:
        ` 'sofort' => $sofortFactory->create(array(
                'factory' => 'sofort',
                'config_key' => '12345:123456:edc788a4316ce7e2ac0ede037aa623d7',
            )),`

And Controller is looks like:

    public function sofortAction()
            {
    $storage = $this->getServiceLocator()->get('payum')->getStorage('Reisesparer\Model\SofortueberWeisung');

    $payment = $storage->create();

    $payment->setNumber(uniqid());
    $payment->setCurrencyCode('EUR');
    $payment->setTotalAmount(123); // 1.23 EUR
    $payment->setDescription('A description');
    $payment->setClientId('anId');
    $payment->setClientEmail('foo@example.com');

    $storage->update($payment);

    $captureToken = $this->getServiceLocator()->get('payum.security.token_factory')->createCaptureToken(
        'sofort', $payment, 'payment_done'
    );
    print_r($captureToken);
    //exit();

    $this->redirect()->toUrl($captureToken->getTargetUrl());
     }

And Model has the following code:

          <?php
              namespace Reisesparer\Model;

              use Payum\Core\Model\Payment;

              class SofortueberWeisung extends Payment
                {
	            protected $id;
                 }

**Comment by makasim** [comment]
duplicates https://github.com/Payum/Payum/issues/661
